services:
  - type: web
    name: task-manager-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: cd task-manager-backend && python -c "import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=int('$PORT'))"
    rootDir: . 